### ISSUE TITLE
[오류] java.lang.IllegalArgumentException: Sheet index (20) is out of range (0..19)

### ISSUE THREAD

**Issue by kuil09** [OpenSourceConsulting/scouter-plugin-server-reporting#1]
안녕하세요. 멋진 플러그인 만들어 주셔서 감사합니다. 
플러그인 설치 후 바로 수동으로 데일리 리포트 생성 커맨드를 수행해 봤습니다.
아래와 같은 오류가 발생하는데 조치방법이 궁금합니다.

[SCOUTER-X] Start Daily Java Report.
java.lang.IllegalArgumentException: Sheet index (20) is out of range (0..19)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetIndex(XSSFWorkbook.java:1382)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetAt(XSSFWorkbook.java:1024)
        at scouter.plugin.server.reporting.report.JavaReport.createExcel(JavaReport.java:58)
        at scouter.plugin.server.reporting.ReportingPlugin.main(ReportingPlugin.java:1050)
[SCOUTER-X] Start Daily Service Report.

아래는 컨피그 설정 내용입니다.
# Reporting
ext_plugin_reporting_drop_table=false
ext_plugin_reporting_logging_enabled=false
ext_plugin_reporting_max_elapsed_time=5000
ext_plugin_reporting_output_dir=D:\scouter\reporting
ext_plugin_reporting_application_name=ELEC_PORTAL_PROD, BI-MATRIX, IJE_ACCT_PROD, IJE_SFA_PROD
ext_plugin_reporting_excel_export=true

**Comment by nices96** [comment]
레포팅 플러그인은 기본적으로 scouter-plugin-server-reporting/src/main/resources/excel 하위의 엑셀 템플릿을 이용하여 레포팅 파일을 생성합니다. 

java_hourly_template.xlsx, java_daily_template.xlsx 파일에 저장된 Sheet의 개수가 20개로 고정되어 있는데, 현재 스카우터 서버에 등록된 Java Agent의 수가 20개를 넘어서 발생하는 오류 입니다.

따라서 scouter-plugin-server-reporting/src/main/resources/excel 하위의 엑셀 템플릿 파일을 수정(Sheet 갯수를 증가)하여 빌드 후 재 적용을 하셔야 할 것 같습니다.

**Comment by kuil09** [comment]
감사합니다. 재빌드가 필요한 부분이군요.

**Comment by kuil09** [comment]
아.. 여기 회사라 DRM 걸리는 부분이 있어서 집가서 해야 겠네요. 흙흙

**Comment by nices96** [comment]
참.. 그리고 ext_plugin_reporting_application_name 값은 하나 입력하셔야 합니다.

**Comment by nices96** [comment]
혹시 에이전트 갯수가 몇개인지 알려주시면 제가 빌드해드릴게요..

**Comment by nices96** [comment]
https://github.com/OpenSourceConsulting/scouter-plugin-server-reporting/releases/download/0.0.4/scouter-plugin-server-reporting-0.0.4.jar 에 에이전트 갯수를 50개로 늘렸습니다. Poi 라이브러리를 사용해서 시트 복사 시 챠트 부분이 정상적이지 않아 부득이하게 템플릿을 작성하여 사용하고 있습니다.

**Comment by kuil09** [comment]
감사합니다!

**Comment by kuil09** [comment]
ext_plugin_reporting_application_name 

이 프로퍼티가 정확히 뭘 의미하는지 모르겠습니다.
지정된 어플리케이션만 리포팅 된다는 의미로 받아들였었습니다. 

댓글로 제공해 주신 플러그인에 
저 프로퍼티 값을 대충 준 상태에서 수동 생성했더니 데이터들이 전부 N/A로 뜨네요.

**Comment by nices96** [comment]
ext_plugin_reporting_application_name는 https://view.officeapps.live.com/op/view.aspx?src=https://github.com/OpenSourceConsulting/scouter-plugin-server-reporting/blob/master/document/sample/monthly/operation_2017.12.xlsx?raw=true 에서와 같이 애플리케이션 이름을 출력하기 위한 파라메타입니다.

그리고 데이터들이 N/A로 뜨는건 여러가지 이유가 있을 수 있겠지만 가장 큰 원인은 해당 시간 또는 일에 해당하는 수집된 데이터가 없어서 그렇습니다.

**Comment by kuil09** [comment]
친절하고 상세하신 답변 감사합니다. :)

**Comment by nices96** [comment]
<img width="1136" alt="screen shot 2018-01-16 at 9 03 22 am" src="https://user-images.githubusercontent.com/2142732/34966095-821707d4-fa9c-11e7-9631-25dd11dc1287.png">

위와 같이 DB Client 프로그램을 이용하여 데이터 적재 여부를 확인할 수 있습니다.

**Comment by nices96** [comment]
java.lang.IllegalArgumentException 오류가 더 이상 발생하지 않는다면 이슈는 Close 시키겠습니다.
